### ISSUE TITLE
缺失词条

### ISSUE THREAD

**Issue by luiyongsheng** [sgalal/opencc-data#1]
似乎還有很多未收錄的詞條
http://www.atm.org.tw/Uploads/201408/53e1a2c00d65b.pdf

**Comment by luiyongsheng** [comment]
http://www.hintoninfo.com.tw/Upload/mag/words.pdf

**Comment by ayaka14732** [comment]
這專案只是收集 OpenCC 的詞典 <https://github.com/BYVoid/OpenCC/tree/master/data/dictionary>，可以在那裏回報問題～
